---
title: "Replication of Study by Young-eun Lee & Susan A. Gelman (2022, Journal of Experimental Child Psychology)"
author: "Mikka Hoffman (m5hoffman@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

<!--[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information. You will likely contact the authors of the original study, so this should be professional and forward facing. It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  -->

The experiment I have chosen was conducted by Lee and Gelman (2022) to investigate whether, for children and adults, behaviors that are seen as violations of property rights when referring to physical property are similarly viewed as violations when referring to digital property. Since data will be collected via SONA, I am proposing replicating only the adult sample from this study. In this experiment, adults and children rated how okay/not okay the actions of a character were after hearing stories about a person who downloaded a digital file that did not belong to them versus a person who took a physical item that did not belong to them. I am focusing on the result that adults found downloading a digital item to be more acceptable than taking a physical item (children’s pattern of evaluations looked very similar to adults’) - evaluating taking a physical item negatively, but a digital item neutrally. This experiment is relevant to my own research interests as I have recently been interested in the development of children’s understanding of digital technology - specifically, I have been thinking about children’s thinking about their own digital privacy/ownership of their digital image in regard to their parents/caregivers sharing recordings of them. Understanding how people understand digital technology as similar or different to non-digital examples is relevant to this line of research. 

All data and protocols are available at <https://osf.io/3g2j4/>, including example stimuli. Adults in this study were presented with six scenarios, randomly presented via Qualtrics, in which a target character either placed a physical item left next to a shared computer into their bag, or downloaded a file from a shared computer onto their own. Participants responded how okay or not okay the action was using a 5-point Likert scale. Three of the scenarios adults read were about physical objects and three were about digital objects (music, movie, book, photo of nature, drawing, and game; the types of items shown in a digital versus physical format were counterbalanced). 

Since the stimuli used in this experiment were written vignettes presented via Qualtrics, I am wondering now if this procedure will still lend itself well to coding a javascript experiment, since that is something I would like to gain experience with. I also see a potential challenge with replicating the stimuli and procedures exactly, since only one example of stimuli is posted on OSF. I anticipate that I may have to reach out to the authors for their full procedure and materials, or recreate them myself. 

Link to repository: <https://github.com/mikkahoffman/lee2022.git>
Link to paper: <https://github.com/mikkahoffman/lee2022/blob/b99ec0bc5b82c91a985fb262e186f7811e3d0c25/original_paper/Lee%26Gelman_2022.pdf> 

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
